default_config:

logger:
  default: info
  logs:
    custom_components: debug

# Load custom card
lovelace:
  mode: yaml
  resources:
    - url: http://127.0.0.1:5000/ha-air-purifier-card.js
      type: module

# Demo fan entity
fan:
  - platform: demo
    name: Air Purifier
